"""create notifications service schema

Revision ID: 30be6e328655
Revises: 
Create Date: 2026-09-26 12:35:05.948559
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '30be6e328655'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS notifications")
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('ix_notification_audit_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False, schema='notifications')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_url', sa.String(length=500), nullable=True),
    sa.Column('template_key', sa.String(length=150), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'deduplication_key', name='uq_notification_dedup'),
    schema='notifications'
    )
    op.create_index('ix_notification_tenant_created', 'notifications', ['tenant_id', 'created_at'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_category'), 'notifications', ['category'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_expires_at'), 'notifications', ['expires_at'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_resource_id'), 'notifications', ['resource_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_source_event_id'), 'notifications', ['source_event_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False, schema='notifications')
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('ix_notification_outbox_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False, schema='notifications')
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'category', 'channel', name='uq_preference'),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_preferences_tenant_id'), 'preferences', ['tenant_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_preferences_user_id'), 'preferences', ['user_id'], unique=False, schema='notifications')
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('stream_message_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='notifications'
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=150), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'deduplication_key', name='uq_schedule_dedup'),
    schema='notifications'
    )
    op.create_index('ix_schedule_due', 'schedules', ['processed_at', 'scheduled_for'], unique=False, schema='notifications')
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title_template', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('allowed_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_category', sa.String(length=100), nullable=False),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_template_key_version'),
    schema='notifications'
    )
    op.create_index('ix_template_active', 'templates', ['key', 'active'], unique=False, schema='notifications')
    template_table = sa.table(
        "templates",
        sa.column("id", sa.UUID()),
        sa.column("key", sa.String()),
        sa.column("version", sa.Integer()),
        sa.column("title_template", sa.String()),
        sa.column("body_template", sa.Text()),
        sa.column("allowed_variables", postgresql.JSONB()),
        sa.column("default_category", sa.String()),
        sa.column("default_severity", sa.String()),
        sa.column("active", sa.Boolean()),
        schema="notifications",
    )
    seeds = [
        ("10000000-0000-4000-8000-000000000001", "contract.activity", "Activitate contractuală", "Contractul {resource_id} a înregistrat acțiunea: {action}.", "CONTRACTS", "INFO"),
        ("10000000-0000-4000-8000-000000000002", "contract.milestone", "Actualizare jalon contractual", "Jalonul {resource_id} a înregistrat acțiunea: {action}.", "CONTRACTS", "WARNING"),
        ("10000000-0000-4000-8000-000000000003", "contract.obligation", "Actualizare obligație contractuală", "Obligația {resource_id} a înregistrat acțiunea: {action}.", "CONTRACTS", "WARNING"),
        ("10000000-0000-4000-8000-000000000004", "contract.payment", "Actualizare plată contractuală", "Plata {resource_id} a înregistrat acțiunea: {action}.", "CONTRACTS", "WARNING"),
        ("10000000-0000-4000-8000-000000000005", "document.uploaded", "Document încărcat", "Documentul {resource_id} a înregistrat acțiunea: {action}.", "DOCUMENTS", "INFO"),
        ("10000000-0000-4000-8000-000000000006", "document.available", "Document disponibil", "Documentul {resource_id} este disponibil după acțiunea: {action}.", "DOCUMENTS", "SUCCESS"),
        ("10000000-0000-4000-8000-000000000007", "document.rejected", "Document respins", "Documentul {resource_id} a fost respins la procesare. Acțiune: {action}.", "DOCUMENTS", "CRITICAL"),
        ("10000000-0000-4000-8000-000000000008", "document.archived", "Document arhivat", "Documentul {resource_id} a fost arhivat. Acțiune: {action}.", "DOCUMENTS", "INFO"),
        ("10000000-0000-4000-8000-000000000009", "legal.deadline", "Termen juridic apropiat", "Resursa juridică {resource_id} necesită atenție: {action}.", "LEGAL", "WARNING"),
        ("10000000-0000-4000-8000-000000000010", "legal.overdue", "Termen juridic depășit", "Resursa juridică {resource_id} este restantă: {action}.", "LEGAL", "CRITICAL"),
        ("10000000-0000-4000-8000-000000000011", "legal.enforcement", "Actualizare executare", "Procedura {resource_id} a înregistrat acțiunea: {action}.", "LEGAL", "WARNING"),
        ("10000000-0000-4000-8000-000000000012", "legal.penalty", "Expunere la penalitate", "Expunerea {resource_id} necesită atenție: {action}.", "LEGAL", "CRITICAL"),
        ("10000000-0000-4000-8000-000000000013", "administrative.event", "Eveniment administrativ", "Evenimentul {resource_id}: {action}.", "ADMINISTRATIVE", "INFO"),
        ("10000000-0000-4000-8000-000000000014", "security.event", "Eveniment de securitate", "Evenimentul de securitate {resource_id}: {action}.", "SECURITY", "CRITICAL"),
    ]
    op.bulk_insert(
        template_table,
        [
            {
                "id": identifier,
                "key": key,
                "version": 1,
                "title_template": title,
                "body_template": body,
                "allowed_variables": ["resource_id", "action"],
                "default_category": category,
                "default_severity": severity,
                "active": True,
            }
            for identifier, key, title, body, category, severity in seeds
        ],
    )
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'recipient_user_id', 'channel', name='uq_delivery'),
    schema='notifications'
    )
    op.create_index('ix_delivery_retry', 'delivery_attempts', ['status', 'next_attempt_at'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_delivery_attempts_tenant_id'), 'delivery_attempts', ['tenant_id'], unique=False, schema='notifications')
    op.create_table('recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_recipient'),
    schema='notifications'
    )
    op.create_index('ix_recipient_inbox', 'recipients', ['tenant_id', 'user_id', 'status', 'created_at'], unique=False, schema='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipient_inbox', table_name='recipients', schema='notifications')
    op.drop_table('recipients', schema='notifications')
    op.drop_index(op.f('ix_notifications_delivery_attempts_tenant_id'), table_name='delivery_attempts', schema='notifications')
    op.drop_index('ix_delivery_retry', table_name='delivery_attempts', schema='notifications')
    op.drop_table('delivery_attempts', schema='notifications')
    op.drop_index('ix_template_active', table_name='templates', schema='notifications')
    op.drop_table('templates', schema='notifications')
    op.drop_index('ix_schedule_due', table_name='schedules', schema='notifications')
    op.drop_table('schedules', schema='notifications')
    op.drop_table('processed_events', schema='notifications')
    op.drop_index(op.f('ix_notifications_preferences_user_id'), table_name='preferences', schema='notifications')
    op.drop_index(op.f('ix_notifications_preferences_tenant_id'), table_name='preferences', schema='notifications')
    op.drop_table('preferences', schema='notifications')
    op.drop_index('ix_notification_outbox_unpublished', table_name='outbox_events', schema='notifications')
    op.drop_table('outbox_events', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_tenant_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_source_event_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_scheduled_for'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_resource_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_expires_at'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_category'), table_name='notifications', schema='notifications')
    op.drop_index('ix_notification_tenant_created', table_name='notifications', schema='notifications')
    op.drop_table('notifications', schema='notifications')
    op.drop_index('ix_notification_audit_tenant_created', table_name='audit_events', schema='notifications')
    op.drop_table('audit_events', schema='notifications')
    # ### end Alembic commands ###
