"""add contract notifications

Revision ID: a180faa2a5ec
Revises: a54d72624076
Create Date: 2026-09-25 08:18:38.177139
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a180faa2a5ec"
down_revision: str | None = "a54d72624076"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "entity_type",
            "entity_id",
            "notification_type",
            name="uq_contract_notifications_business_key",
        ),
        schema="contracts",
    )
    op.create_index(
        "ix_contract_notifications_tenant_read",
        "notifications",
        ["tenant_id", "read_at"],
        unique=False,
        schema="contracts",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_contract_notifications_tenant_read", table_name="notifications", schema="contracts"
    )
    op.drop_table("notifications", schema="contracts")
    # ### end Alembic commands ###
