"""create contracts domain tables

Revision ID: a54d72624076
Revises: 20260925_0001
Create Date: 2026-09-25 00:03:20.425146
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "a54d72624076"
down_revision: str | None = "20260925_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False, schema='contracts')
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'TERMINATED', 'CANCELLED', name='contract_status', schema='contracts'), nullable=False),
    sa.Column('responsible_department_id', sa.UUID(), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'contract_number', name='uq_contracts_tenant_number'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False, schema='contracts')
    op.create_index('ix_contracts_tenant_end_date', 'contracts', ['tenant_id', 'end_date'], unique=False, schema='contracts')
    op.create_index('ix_contracts_tenant_status', 'contracts', ['tenant_id', 'status'], unique=False, schema='contracts')
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index('ix_contract_outbox_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False, schema='contracts')
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('party_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_parties_tenant_id'), 'parties', ['tenant_id'], unique=False, schema='contracts')
    op.create_table('amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('amendment_number', sa.String(length=100), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=False),
    sa.Column('value_change', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('end_date_change', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_amendments_contract_id'), 'amendments', ['contract_id'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_amendments_tenant_id'), 'amendments', ['tenant_id'], unique=False, schema='contracts')
    op.create_table('contract_parties',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['contracts.parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', 'party_id', 'role'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_contract_parties_tenant_id'), 'contract_parties', ['tenant_id'], unique=False, schema='contracts')
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='milestone_status', schema='contracts'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index('ix_contract_milestones_tenant_due', 'milestones', ['tenant_id', 'due_date'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_milestones_contract_id'), 'milestones', ['contract_id'], unique=False, schema='contracts')
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='contract_obligation_status', schema='contracts'), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index('ix_contract_obligations_tenant_due', 'obligations', ['tenant_id', 'due_date'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_obligations_contract_id'), 'obligations', ['contract_id'], unique=False, schema='contracts')
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'APPROVED', 'PAID', 'REJECTED', 'CANCELLED', name='payment_status', schema='contracts'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index('ix_contract_payments_tenant_due', 'payments', ['tenant_id', 'due_date'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_payments_contract_id'), 'payments', ['contract_id'], unique=False, schema='contracts')
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'TERMINATED', 'CANCELLED', name='contract_status', schema='contracts'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'TERMINATED', 'CANCELLED', name='contract_status', schema='contracts'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='contracts'
    )
    op.create_index(op.f('ix_contracts_status_history_contract_id'), 'status_history', ['contract_id'], unique=False, schema='contracts')
    op.create_index(op.f('ix_contracts_status_history_tenant_id'), 'status_history', ['tenant_id'], unique=False, schema='contracts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_status_history_tenant_id'), table_name='status_history', schema='contracts')
    op.drop_index(op.f('ix_contracts_status_history_contract_id'), table_name='status_history', schema='contracts')
    op.drop_table('status_history', schema='contracts')
    op.drop_index(op.f('ix_contracts_payments_contract_id'), table_name='payments', schema='contracts')
    op.drop_index('ix_contract_payments_tenant_due', table_name='payments', schema='contracts')
    op.drop_table('payments', schema='contracts')
    op.drop_index(op.f('ix_contracts_obligations_contract_id'), table_name='obligations', schema='contracts')
    op.drop_index('ix_contract_obligations_tenant_due', table_name='obligations', schema='contracts')
    op.drop_table('obligations', schema='contracts')
    op.drop_index(op.f('ix_contracts_milestones_contract_id'), table_name='milestones', schema='contracts')
    op.drop_index('ix_contract_milestones_tenant_due', table_name='milestones', schema='contracts')
    op.drop_table('milestones', schema='contracts')
    op.drop_index(op.f('ix_contracts_contract_parties_tenant_id'), table_name='contract_parties', schema='contracts')
    op.drop_table('contract_parties', schema='contracts')
    op.drop_index(op.f('ix_contracts_amendments_tenant_id'), table_name='amendments', schema='contracts')
    op.drop_index(op.f('ix_contracts_amendments_contract_id'), table_name='amendments', schema='contracts')
    op.drop_table('amendments', schema='contracts')
    op.drop_index(op.f('ix_contracts_parties_tenant_id'), table_name='parties', schema='contracts')
    op.drop_table('parties', schema='contracts')
    op.drop_index(op.f('ix_contracts_outbox_events_tenant_id'), table_name='outbox_events', schema='contracts')
    op.drop_index(op.f('ix_contracts_outbox_events_aggregate_id'), table_name='outbox_events', schema='contracts')
    op.drop_index('ix_contract_outbox_unpublished', table_name='outbox_events', schema='contracts')
    op.drop_table('outbox_events', schema='contracts')
    op.drop_index('ix_contracts_tenant_status', table_name='contracts', schema='contracts')
    op.drop_index('ix_contracts_tenant_end_date', table_name='contracts', schema='contracts')
    op.drop_index(op.f('ix_contracts_contracts_tenant_id'), table_name='contracts', schema='contracts')
    op.drop_table('contracts', schema='contracts')
    op.drop_index(op.f('ix_contracts_audit_events_tenant_id'), table_name='audit_events', schema='contracts')
    op.drop_index(op.f('ix_contracts_audit_events_entity_id'), table_name='audit_events', schema='contracts')
    op.drop_table('audit_events', schema='contracts')
    # ### end Alembic commands ###
